### ISSUE TITLE
error on start on debian Buster.

### ISSUE THREAD

**Issue by dominix** [MaxKellermann/ferm#48] opened 2019-06-12 23:40 UTC
on debian buster ferm stop with an error on start.
~~~
iptables-restore v1.8.2 (nf_tables): 
line 94: RULE_APPEND failed (Invalid argument): rule in chain INPUT
Failed to run /sbin/iptables-restore
~~~
it works if I do
~~~
ferm --noexec --lines /etc/ferm/ferm.conf > /tmp/myrules
iptables-legacy-restore < /tmp/myrules
~~~

I have set FAST=no and CACHE=no in /etc/default/ferm so it start correctly now. It is more an avoidance than a fix ...

**Comment by landryb** [comment] 2019-07-11 13:59
I think this is related to the default switch to nftables in buster, cf https://www.debian.org/releases/buster/amd64/release-notes/ch-whats-new.en.html#nftables

**Comment by 532910** [comment] 2019-08-20 01:27
@dominix, `update-alternatives` for `iptables` and `ip6tables` for `-legacy` ones.

**Comment by MaxKellermann** [comment] 2019-10-25 08:31
Duplicate of https://github.com/MaxKellermann/ferm/issues/47 ?

**Comment by MaxKellermann** [comment] 2019-11-22 19:08
47b78b683d3d8a33e37ff8bf1816054906966302

**Closed by MaxKellermann** 2019-11-22 19:08 UTC
